version: '3'

tasks:
  pack:
    desc: Package and prepare assets for the game.
    cmds: []

  preview:
    desc: Preview game assets.
    cmds:
      - go run './cmd/studio' preview ./ {{.CLI_ARGS}}

  run:
    desc: Run the game.
    cmds:
      - go run './cmd/game'
