version: '3'

tasks:
  pack:
    desc: Prepare assets for the game.
    cmds:
      - go run './cmd/studio' pack ./ {{.CLI_ARGS}}

  webpack:
    desc: Prepare web assets for the game.
    cmds:
      - mkdir -p 'assets/web'
      - cp 'resources/ui/images/icon.png' 'assets/web/favicon.png'
      - cp 'resources/web/main.css' 'assets/web/main.css'
      - cp 'resources/web/main.js' 'assets/web/main.js'
      - cp 'resources/web/index.html' 'assets/index.html'
      - cp 'resources/web/wasm_exec.js' 'assets/web/wasm_exec.js'

  wasm:
    desc: Build the game executable for the web.
    env:
      GOOS: js
      GOARCH: wasm
    cmds:
      - go build -o './assets/web/main.wasm' './cmd/game'

  preview:
    desc: Preview game assets.
    cmds:
      - go run './cmd/studio' preview ./ {{.CLI_ARGS}}

  run:
    desc: Run the game.
    cmds:
      - go run './cmd/game'

  web:
    desc: Run a web server to serve the game.
    cmds:
      - go run 'github.com/mokiat/httpserv@v1.0.0' -dir './assets' -host '127.0.0.1'
